# - name: "Fetches details about one or multiple AvailabilityDomain resources in Oracle Cloud Infrastructure"
#   oracle.oci.oci_identity_availability_domain_facts:
#     compartment_id: "{{ oci.compartment_id }}"
#   register: oci_availability_domains

# - name: "Debug OCI AvailabilityDomain resources"
#   ansible.builtin.debug:
#     msg: "{{ oci_availability_domains }}"

- name: "get VCNs"
  oracle.oci.oci_network_vcn_facts:
    compartment_id: "{{ oci.compartment_id }}"
  register: result

- name: "Debug VCNs"
  ansible.builtin.debug:
    msg: "{{ result }}"
