# - name: "Get VCNs"
#   oracle.oci.oci_network_vcn_facts:
#     compartment_id: "{{ oci.compartment_id }}"
#   register: vcn_list

# - name: "Filter the target VCN"
#   ansible.builtin.set_fact:
#     vcn_id: "{{ vcn_list | community.general.json_query(vcn_filter_expression)}}"
#   vars:
#     vcn_filter_expression: "vcns[?display_name=='{{ oci.vcn.display_name }}'].id | [0]"

- name: "Create a VCN"
  oracle.oci.oci_network_vcn:
    compartment_id: "{{ oci.compartment_id }}"
    display_name: "{{ oci.vcn.display_name }}"
    cidr_block: "{{ vcn_cidr_block }}"
    dns_label: "{{ oci.vcn.dns_label }}"
  register: vcn_createion_result

- name: "Get OCID of the created VCN"
  ansible.builtin.set_fact:
    vcn_id: "{{ vcn_createion_result.vcn.id }}"

- name: "Create an Internet Gateway"
  oracle.oci.oci_network_internet_gateway:
    compartment_id: "{{ oci.compartment_id }}"
    vcn_id: "{{ vcn_id }}"
    name: "{{ oci.internet_gateway.name }}"
    is_enabled: true
    state: 'present'
  register: ig_creation_result

- set_fact:
    ig_id: "{{ ig_creation_result.internet_gateway.id }}"
